"use client"


import { DndProvider } from 'react-dnd'
import './globals.css'
import { Inter } from 'next/font/google'
import { HTML5Backend } from 'react-dnd-html5-backend'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <DndProvider backend={HTML5Backend}>
        <body className={inter.className}>{children}</body>
      </DndProvider>
    </html>
  );
}
